export const theme = {
  colors: {
    primary: '#2196F3',
    secondary: '#03A9F4',
    success: '#4CAF50',
    danger: '#F44336',
    warning: '#FFC107',
    info: '#00BCD4',
    light: '#F5F5F5',
    dark: '#212121',
    gray: '#9E9E9E',
    grayLight: '#E0E0E0',
    grayDark: '#616161',
    white: '#FFFFFF',
    black: '#000000',
    background: '#FFFFFF',
    text: '#212121',
    border: '#E0E0E0',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  typography: {
    fontFamily: {
      regular: 'System',
      medium: 'System',
      bold: 'System',
    },
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 30,
    },
    lineHeight: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 28,
      xl: 32,
      xxl: 36,
    },
  },
  borderRadius: {
    xs: 2,
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    round: 9999,
  },
  shadows: {
    none: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.18,
      shadowRadius: 1.0,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
  },
  // Common component styles
  components: {
    container: {
      padding: 16,
      backgroundColor: '#FFFFFF',
    },
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      padding: 16,
      marginVertical: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    input: {
      height: 48,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      paddingHorizontal: 12,
      marginBottom: 16,
      backgroundColor: '#FFFFFF',
    },
    button: {
      primary: {
        backgroundColor: '#2196F3',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
      },
      secondary: {
        backgroundColor: '#03A9F4',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
      },
      success: {
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
      },
      danger: {
        backgroundColor: '#F44336',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
      },
      text: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    },
    stepIndicator: {
      dot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#E0E0E0',
        marginHorizontal: 5,
      },
      activeDot: {
        backgroundColor: '#2196F3',
        transform: [{ scale: 1.2 }],
      },
      completedDot: {
        backgroundColor: '#4CAF50',
      },
    },
    formSection: {
      title: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 16,
        color: '#212121',
      },
      container: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
      },
    },
    timer: {
      container: {
        padding: 12,
        backgroundColor: '#F5F5F5',
        borderRadius: 8,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      },
      text: {
        fontWeight: 'bold',
        color: '#2196F3',
        fontSize: 16,
      },
      icon: {
        marginRight: 8,
        color: '#2196F3',
      },
    },
  },
};
